// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopCustomerBooking
{
    public int CustomerBookingId { get; set; }

    public int? MemberId { get; set; }

    public int? OrderId { get; set; }

    public string BookingTime { get; set; }

    public int? ServiceCatNum { get; set; }

    public int? BookingStatus { get; set; }

    public virtual ShopBookingStatus BookingStatusNavigation { get; set; }

    public virtual ShopOrderTotalTable Order { get; set; }
}