// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopNoserviceDate
{
    public int ClosedDateId { get; set; }

    public int? BookingId { get; set; }

    public string ClosedDate { get; set; }

    public virtual ShopAdminBooking Booking { get; set; }
}