// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopAdminBooking
{
    public int? ProductId { get; set; }

    public int BookingId { get; set; }

    public DateTime? OpenMonth { get; set; }

    public virtual GameProductTotal Product { get; set; }

    public virtual ICollection<ShopNoserviceDate> ShopNoserviceDate { get; set; } = new List<ShopNoserviceDate>();

    public virtual ICollection<ShopOpenBookingTime> ShopOpenBookingTime { get; set; } = new List<ShopOpenBookingTime>();
}