// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopBookingStatus
{
    public int StatusId { get; set; }

    public string StatusText { get; set; }

    public virtual ICollection<ShopCustomerBooking> ShopCustomerBooking { get; set; } = new List<ShopCustomerBooking>();
}