// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class Uploadsuccess
{
    public int Uploaded { get; set; }

    public string FileName { get; set; }

    public string Url { get; set; }
}